# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Pipeline

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Installing Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Installing Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install psutil
    - name: Testing with Unittest
      run: |
        unittest
